# Herencia en clase

En el presente notebook encontrarán ejemplos de herencia en clases, polimorfismo, encapsulación, abstracción.

## Vectores

Se muestra inicialmente un ejemplo de vectores en el que el vector 3d Hereda la clase de vector 2D para generalizarla

In [1]:
class Vector2D:
    def __init__(self, x, y):
        self.x = x
        self.y = y
    def __str__(self):
        return(f"({self.x},{self.y})")
    def magnitud(self):
        return(pow(self.x**2+self.y**2,0.5))

In [2]:
v1 = Vector2D(1,2)
print(v1)
print(v1.magnitud())

(1,2)
2.23606797749979

In [28]:
class Vector3D(ABC, Vector2D):
    def __init__(self, x, y, z):
        super().__init__(x, y)
        self.z = z
    def __str__(self):
        cadena = super().__str__()[:-1]+f",{self.z})"
        return(cadena)
    @abstractmethod
    def magnitud(self):
        return((super().magnitud()**2+self.z**2)**0.5)

In [31]:
class VectorTaxi(Vector3D):
    def magnitud(self):
        return((abs(self.x))+(abs(self.y))+(abs(self.z)))

In [33]:
class VectorEuclides(Vector3D):
    def magnitud(self):
        return(super().magnitud())

In [34]:
v2 = VectorEuclides(1,2,5)
print(v2)
print(v2.magnitud())

(1,2,5)
5.477225575051661

In [32]:
v2 = VectorTaxi(1,2,5)
print(v2)
print(v2.magnitud())

(1,2,5)
8

In [1]:
import numpy as np

In [7]:
A = np.random.rand(5,7)
np.savetxt("matriz.csv",A,delimiter=",")

In [12]:
!cat matriz.csv

5.629010852508287144e-02,8.235596476009657829e-01,4.665182524255017116e-01,5.834396538218455941e-02,6.986527684760717172e-01,6.579460933207149642e-01,7.219477363148540938e-03
4.739390060572724606e-01,8.483495920599820606e-01,5.329874786004314968e-01,6.380215609820435452e-01,4.123437596692929308e-01,6.915770090207918885e-01,6.695394244621837299e-01
4.479731173260619315e-01,6.077482250966879107e-01,4.275879109160185543e-02,4.754652837882085148e-01,5.619560301273927028e-01,1.785558178864332657e-02,5.777969650679967151e-01
4.588480354140671569e-01,8.825877352242269547e-01,1.990336479562256899e-01,1.603077298393837946e-01,9.637498362918891504e-01,9.406678341731072868e-01,1.322059529056689442e-01
6.242823267756006933e-01,7.261204831199031817e-01,4.396553970389386334e-01,2.881924366957577810e-02,9.723814617812781558e-01,5.722418157084331325e-01,1.654683746382634713e-01

In [11]:
np.genfromtxt("matriz.csv",delimiter=",",usecols=[0,1,3])

array([[0.05629011, 0.82355965, 0.05834397],
       [0.47393901, 0.84834959, 0.63802156],
       [0.44797312, 0.60774823, 0.47546528],
       [0.45884804, 0.88258774, 0.16030773],
       [0.62428233, 0.72612048, 0.02881924]])

In [16]:
f = open("log.txt","a")
print("Hola de nuevo de nuevo Log file", file=f)
f.close()

In [18]:
open("log.txt").read()

'Hola de nuevo Log file\nHola de nuevo de nuevo Log file\n'

In [19]:
with open("log2.txt","a") as f:
    print("Hola de nuevo de nuevo Log file", file=f)

In [24]:
np.genfromtxt("raw.csv")

array([[1.3263    , 1.8620857 , 3.56261467, ..., 2.86539965, 4.7738198 ,
        3.53937285],
       [1.34149   , 1.78655768, 2.35476558, ..., 4.68114817, 3.21549438,
        3.97267229],
       [1.33034   , 1.82618744, 3.03799709, ..., 1.37555387, 4.36332004,
        2.98854614],
       ...,
       [1.31469   , 1.81256374, 1.83043853, ..., 4.94588229, 3.6561804 ,
        2.51979689],
       [1.29903   , 1.98703052, 1.46531626, ..., 4.06657492, 4.52332245,
        3.43531235],
       [1.34212   , 1.80503606, 3.82814723, ..., 1.59234561, 1.7857543 ,
        2.5275172 ]], shape=(24000, 41))

In [30]:
import pandas as pd
pd.read_csv("winequality-red.csv",delimiter=";")

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [21]:
import pandas as pd
pd.read_csv("resultElections.csv")

,Code,Constituency,Candidate,Party,EVM Votes,Postal Votes,Total Votes,% Votes,Round,Last Updated Time,Last Updated Date
0,S221,GUMMIDIPOONDI - 1,T.J.GOVINDARAJAN,Dravida Munnetra Kazhagam,61922,570,62492,26.88,26/26,11:27 PM,04/05/2026
1,S221,GUMMIDIPOONDI - 1,SUDHAKAR.V,All India Anna Dravida Munnetra Kazhagam,65894,481,66375,28.55,26/26,11:27 PM,04/05/2026
2,S221,GUMMIDIPOONDI - 1,M.JAGADEESAN,Bahujan Samaj Party,695,2,697,0.30,26/26,11:27 PM,04/05/2026
3,S221,GUMMIDIPOONDI - 1,"R.SRIDAR. B.L.,",Naam Tamilar Katchi,4707,49,4756,2.05,26/26,11:27 PM,04/05/2026
4,S221,GUMMIDIPOONDI - 1,SDK SANKAR,Aanaithinthiya Jananayaka Pathukappu Kazhagam,593,6,599,0.26,26/26,11:27 PM,04/05/2026
...,...,...,...,...,...,...,...,...,...,...,...
4252,S22234,KILLIYOOR - 234,AJAI (ALIAS) NAGARAJAN,Independent,240,1,241,0.14,23/23,11:30 PM,04/05/2026
4253,S22234,KILLIYOOR - 234,BERRILA. L,Independent,193,4,197,0.11,23/23,11:30 PM,04/05/2026
4254,S22234,KILLIYOOR - 234,BABY RAJ. P,Independent,157,5,162,0.09,23/23,11:30 PM,04/05/2026
4255,S22234,KILLIYOOR - 234,JUSTIN. M,Independent,188,1,189,0.11,23/23,11:30 PM,04/05/2026
4256,S22234,KILLIYOOR - 234,NOTA,None of the Above,491,11,502,0.28,23/23,11:30 PM,04/05/2026

In [20]:
!cat log2.txt

Hola de nuevo de nuevo Log file

In [ ]:
from abc import ABC, abstractmethod

class FuncionarioUQ(ABC):
    def __init__(self, nombres, apellidos, id, fecha_ingreso):
        self.name = nombres +" "+apellidos
        self.alias = nombres
        nombre1 = nombres.split()[0]
        try:
            nombre2 = nombres.split()[1]
        except IndexError:
            nombre2 = ""
        apellido1 = apellidos.split()[0]
        apellido2 = apellidos.split()[1]
        if nombre2 != "":
            correo = nombre1 + nombre2[0] + "." + apellido1 + apellido2[0]
        else:
            correo = nombre1 + "." + apellido1 + apellido2[0]
        self.correo = correo.lower()
        self.id = id
        self.ingreso = fecha_ingreso
    @abstractmethod
    def __str__(self):
        cadena = f"{self.name}\nIngreso: {self.ingreso}"
        return(cadena)
    
class Asalariado(ABC):
    def __init__(self, contrato, categoria, estado):
        self._contrato = contrato
        self._estado = estado
        self._categoria = categoria
        
    @property
    def contrato(self):
        return(self._contrato)
    @property
    def estado(self):
        return(self._estado)
    @property
    def categoria(self):
        return(self._categoria)
    @property
    def salario(self):
        return(1000000)
    def ascenso(self,documentacion):
        if documentacion==True:
            self._categoria="NUEVA CATEGORÍA"
    @estado.setter
    def estado(self, nuevo_estado):
        if type(nuevo_estado) == str:
            self._estado = nuevo_estado
        else:
            raise ValueError("El estado debe ser texto")
    @abstractmethod
    def __str__(self):
        cadena = f"Tipo de contrato: {self.contrato}\nEstado: {self.estado}\nSalario categoría {self.categoria}:\
    {self.salario}"
        return(cadena)
        
class EstudianteUQ(FuncionarioUQ):
    def __init__(self, nombres, apellidos, id, fecha_ingreso, carrera, semestres, notas):
        super().__init__(nombres, apellidos, id, fecha_ingreso)
        self.mail = self.correo + "@uqvirtual.edu.co"
        self.carrera = carrera
        self.semestres = semestres
        self.notas = notas
    def __str__(self):
        cadena = f"Estudiante Uniquindiano: {super().__str__()}\nmail: {self.mail}\nCarrera: {self.carrera}"
        return(cadena)
    @classmethod
    def Ingreso(cls, nombres, apellidos, carrera):
        semestres = 1
        notas = []
        id = 1890
        fecha_ingreso = "06/03/2026"
        return cls(nombres, apellidos, id, fecha_ingreso, carrera, semestres, notas)
    def nuevo_semestre(self):
        print("Paga Matricula")
        print("Registra Materias")
    
class DocenteUQ(FuncionarioUQ, Asalariado):
    def __init__(self, nombres, apellidos, id, fecha_ingreso, facultad, categoria, contrato, estado):
        FuncionarioUQ.__init__(self, nombres, apellidos, id, fecha_ingreso)
        Asalariado.__init__(self, contrato, categoria, estado)
        self.mail = self.correo + "@uniquindio.edu.co"
        self.facultad = facultad
    def __str__(self):
        cadena = f"Docente {self.categoria} Uniquindiano: {FuncionarioUQ.__str__(self)}\nmail:\
    {self.mail}\nFacultad: {self.facultad}"
        cadena2 = Asalariado.__str__(self)
        return(cadena+"\n"+cadena2)
    def nuevo_semestre(self):
        print("Acepta Carga")
        print("Firma contrato")

In [21]:
andres = EstudianteUQ("Andres", "Salazar Torres", 1094934548, "23/01/2000", "Fisica", 4, 
                      [{"Matematicas Fundamentales":4, "Introduccion a la Fisica":4.5, "Geometria Analitica":3, "Uniquindianidad":2.4},
                       {"Fisica 1":4, "Calculo 1":5, "Proyecto de Curso 1":3},
                       {"Fisica 2":3, "Calculo 2":4,"Lectura":5, "Algebra Lineal":4}])
print(andres)

Estudiante Uniquindiano: Andres Salazar Torres
Ingreso: 23/01/2000
mail: andres.salazart@uqvirtual.edu.co
Carrera: Fisica

In [17]:
nestor = EstudianteUQ.Ingreso("Nestor", "Torres García", "Física")
print(nestor.semestres)

1

In [37]:
andres = EstudianteUQ("Andres", "Salazar Torres", 1094934548, "23/01/2000", "Fisica", 4, 
                      [{"Matematicas Fundamentales":4, "Introduccion a la Fisica":4.5, "Geometria Analitica":3, "Uniquindianidad":2.4},
                       {"Fisica 1":4, "Calculo 1":5, "Proyecto de Curso 1":3},
                       {"Fisica 2":3, "Calculo 2":4,"Lectura":5, "Algebra Lineal":4}])
santiago = DocenteUQ("Santiago", "Echeverri Arteaga", 1094927502, "02/08/2019", "Ciencias Básicas", "Catedrático", "Asociado", "Activo")
#print(andres,"\n")
#santiago.estado = "Retirado"
#print(santiago)

Julio = EstudianteUQ.Ingreso("Julio", "Sanchez Santamaria", "Química")
print(Julio)

Estudiante Uniquindiano: Julio Sanchez Santamaria
Ingreso: 06/03/2026
mail: julio.sanchezs@uqvirtual.edu.co
Carrera: Química

## Clase Partícula

La clase partícula incorpora encapsulación por medio del decorador `@property` con lo que dichas variables pasan a ser privadas y se establece automáticamente un decorador con el mismo nombre de la variable (pero sin los __) y un .setter al final. Este decorador permite decorar algún método con el nombre de la variable para permitir cambiar el valor de dicho atributo para alguna instancia de la clase por fuera de su definición. Además, al usar el decorador property en algún método con el mismo nombre se establece lo que sería el `getter`, esto es, la forma en que se accede a su valor por fuera de la definición.

Por otro lado, de está definiendo la clase carga eléctrica con herencia, por lo que hereda todos los métodos de la clase padre. Además se usa el decorador `@classmethod`, la cual es útil para herencia y para casos donde no se desea acceder a atributos de la instancia (del `self`) sino de la clase como tal (Crear la clase o acceder a métodos).

Finalmente se ven dos partículas que tienen herencia múltiple, en donde se aprecia que a pesar de que la carga es una clase privada, se permite usar dicha variable en la definición de la clase

In [55]:
e2 = Electron(1,2)
print(e2.energia_cinetica)
e2.velocidad = 10
print(e2.energia_cinetica)

2.0
50.0

In [61]:
class Particula:
    def __init__(self, masa, velocidad):
        self._masa = masa  # Atributo privado
        self._velocidad = velocidad  # Atributo privado

    # Getter para masa
    @property
    def masa(self):
        return self._masa
    
    # Getter para velocidad
    @property
    def velocidad(self):
        return self._velocidad

    # Setter para velocidad
    @velocidad.setter
    def velocidad(self, nueva_velocidad):
        if nueva_velocidad < 0:
            raise ValueError("La velocidad no puede ser negativa.")
        self._velocidad = nueva_velocidad

    # Método decorado para calcular la energía cinética
    @property
    def energia_cinetica(self):
        return 0.5 * self._masa * self._velocidad**2

class CargaElectrica:
    def __init__(self, carga):
        self._carga = carga

    @property
    def carga(self):
        return self._carga

class Electron(Particula, CargaElectrica):
    def __init__(self, masa, velocidad, carga=-1.602e-19):
        Particula.__init__(self, masa, velocidad)
        CargaElectrica.__init__(self, carga)

    @classmethod
    def desde_velocidad(cls, velocidad):
        masa_electron = 9.10938356e-31  # masa del electrón en kg
        return cls(masa_electron, velocidad)
    
class Muon(Electron):
    def __init__(self, masa, velocidad, carga=-1.602e-19):
        super().__init__(masa, velocidad, carga)




# Aplicación de la clase con el setter
e1 = Electron(1,2)
m1 = Muon.desde_velocidad(12)
print(type(m2))
electron_rapido = Electron.desde_velocidad(3e6)  # Crear electrón con velocidad 3e6 m/s

print(f"Velocidad inicial del electrón: {electron_rapido.velocidad:.2e} m/s")
print(f"Masa del electrón: {electron_rapido.masa:.2e} kg")

<class '__main__.Muon'>
Velocidad inicial del electrón: 3.00e+06 m/s
Masa del electrón: 9.11e-31 kg

In [63]:
electron_rapido.velocidad = 1e6  # Cambiar la velocidad del electrón
electron_rapido.velocidad

1000000.0

In [9]:
print(f"Nueva energía cinética: {electron_rapido.energia_cinetica:.2e} J")

Nueva energía cinética: 4.55e-19 J

In [10]:
# Al llamar desde_velocidad desde la subclase Muon, cls será Muon
muon_rapido = Muon.desde_velocidad(3e6)  # Crea un muón con velocidad 3e6 m/s
print(f"El muon es tipo de dato {type(muon_rapido)}") # o probar con isinstance(muon_rapido, Muon)

El muon es tipo de dato <class '__main__.Muon'>

In [11]:
# Si no se necesita acceso a la clase ni a la instancia

class Matematica:
    @staticmethod
    def suma(a, b):
        return a + b

print(Matematica.suma(5, 3))

8

## Métodos Abstractos

Se usa el decorador `@abstractmethod` y se hereda de la clase `ABC` para hacer la clase Model abstracta, esto es, que no se puedan definir instancias de Model, pero que sus métodos sean útiles en las clases heredadas. Se aprecia que se está usando en la clase `Model` un atributo que es `tabla`, el cual no se define en el constructor ni en la clase heredada en el constructor, pero si en el contexto de la clase. Además, al usar el decorador `@abstractmethod` sobre un método (Usualmente en blanco) se exige a las clases que heredan que definan dicho método.

In [65]:
from abc import ABC, abstractmethod

class Model(ABC):
    @property
    @abstractmethod
    def tabla(self):
        pass
    
    @abstractmethod
    def guardar(self):
        pass
    
    @classmethod
    def buscar_por_id(self, _id):
        print(f"Buscando por id {_id} en la tabla {self.tabla}")
        
class Usuario(Model):
    tabla = "Usuario"
    
    def guardar(self):
        print("Guardando usuario")
        
#modelo = Model()
usuario = Usuario()
usuario.guardar()
usuario.buscar_por_id(123)

Guardando usuario
Buscando por id 123 en la tabla Usuario